FactoryBot Migration (#20)
* Add Rubocop to Project
Addresses issues raised by linting.
* Safe Library Upgrades
Factory Girl > 4.4 causes linting errors:
```
FactoryGirl::InvalidFactoryError:
  The following factories are invalid:

  * allscripts_unity_client_parameters - undefined method `save!' for ...
```

Allowing Rails 5 also causes dates to be represented differently,
interestingly enough, but this library is only used by Rails 4
applications at the moment, so safe to bind.

* Resolve Linting Issue
* FactoryGirl -> FactoryBot
* Bump Version
* Use fetch over key? and ?: